#### Nama = `Ahmad Hamdani`
#### Nim = `233307092`
#### Kelas = `4D`

1. Buat file .ipynb, lalu lakukan instalasi library NumPy (disarankan menggunakan
virtual environtment). Beri nama dan kelas anda pada baris paling atas.

2. Setelah instalasi library NumPy berhasil, jalankan kode di bawah ini dengan
terlebih dahulu mengimpor library numpy dengan alias np

In [49]:
import numpy as np
a = np.array([1,2,3])

3. Membuat array dengan isi 0.

In [50]:
np.zeros(2)

array([0., 0.])

4. Membuat array dengan isi 1.

In [51]:
np.ones(2)

array([1., 1.])

5. Membuat array dengan rentang elemen tertentu.

In [52]:
np.arange(5)

array([0, 1, 2, 3, 4])

6. Membuat array rentang elemen dengan step size tertentu, misal setiap 2 step.

In [53]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

7. Membuat array dengan nilai yang diberi jarak linier dalam interval tertentu,
misal 5.

In [54]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

8. Menentukan tipe data tertentu untuk sebuah array.


In [55]:
x = np.ones(2, dtype=np.float64)
x

array([1., 1.])

9. Mengurutkan elemen array.


In [56]:
arr = np.array([2,1,5,3,7,4,8,6])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

10. Menggabungkan array satu dimensi.


In [57]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

11. Menggabungkan array multi dimensi.


In [58]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6]])


12. Mengetahui jumlah sumbu (axes) atau dimensi array.


In [59]:
array_example = np.array([
  [[0, 1, 2, 3],
   [4, 5, 6, 7]],
  [[0, 1, 2, 3],
   [4, 5, 6, 7]],
  [[0 ,1 ,2, 3],
   [4, 5, 6, 7]]
])

array_example.ndim

3

13. Mengetahui jumlah total elemen array dari soal no 12.


In [60]:

array_example.size

24

14. Menampilkan tupel bilangan bulat yang menunjukkan jumlah elemen yang
disimpan di setiap dimensi array.


In [61]:
a = np.arange(6)
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


15. Membentuk ulang array. Misalnya, dari satu dimensi menjadi dua dimensi
(tiga baris dan dua kolom).

In [62]:
np.reshape(a, newshape=(2, 3), order='C')

C:\Users\ACER\AppData\Local\Temp\ipykernel_17688\3067619039.py:1: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  np.reshape(a, newshape=(2, 3), order='C')


array([[0, 1, 2],
       [3, 4, 5]])

16. Membalikkan (transpose) atau menubah sumbu array soal no 14.


In [63]:
b.transpose()

array([[0, 2, 4],
       [1, 3, 5]])

17. Membentuk ulang array dengan shape baru lagi.


In [64]:
a = np.array([1,2,3,4, 5, 6])
a.shape

(6,)

In [65]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

18. Indexing NumPy.


In [66]:
data = np.array([1,2,3])
data[1]

np.int64(2)

19. Menampilkan posisi elemen tertentu dalam sebuah array pada soal no 17. <br/>
a. Mengambil elemen dari indeks 0 hingga 1 (indeks 2 tidak termasuk).<br/>
b. Mengambil elemen dari indeks 1 hingga akhir.<br/>
c. Mengambil dua elemen terakhir.


In [67]:
a = np.array([1,2,3,4, 5, 6])
print(a[0:2])

[1 2]


In [68]:
print(a[1:6])

[2 3 4 5 6]


In [69]:
print(a[4:6])

[5 6]


20. Reverse array 1D dan 2D.

In [70]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.flip(arr)

array([8, 7, 6, 5, 4, 3, 2, 1])

In [71]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
np.flip(arr_2d)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

<strong>B. Soal Latihan
</strong>

21. Buatlah kode reshape python sesuai dengan gambar sbb:


In [72]:
arr = np.array([2, 3, 4, 5, 6, 7, 8, 9, 10])
np.reshape(arr, (3, 3))

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

22. Buatlah kode concatenate python sesuai dengan gambar sbb:

In [73]:
array_example_a = np.array([
  [0, 1, 3],
  [5, 7, 9],
])



print(np.concatenate((array_example_a, array_example_a), axis=1))

[[0 1 3 0 1 3]
 [5 7 9 5 7 9]]


23. Buatlah kode python sesuai dengan gambar sbb:

In [74]:
array_1 = np.array([
  [5, 6, 9],
  [21, 18, 27],
])

array_2 = np.array([
  [15, 33, 24],
  [4, 7, 1],
])
print(f"Array 1 :\n {array_1}")
print(f"\nArray 2 :\n {array_2}")
print(f"\nArray 1 + Array 2 : \n{array_1 + array_2}")

# print(np.concatenate((array_1, array_1), axis=1))

Array 1 :
 [[ 5  6  9]
 [21 18 27]]

Array 2 :
 [[15 33 24]
 [ 4  7  1]]

Array 1 + Array 2 : 
[[20 39 33]
 [25 25 28]]


24. Buatlah array NumPy dengan elemen dari 10 hingga 30.


In [75]:
arr = np.arange(10, 31)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


25. Buatlah array NumPy dengan elemen dari 0 hingga 30 dengan step size 3.


In [76]:
arr = np.arange(0, 31, step=3)
print(arr)

[ 0  3  6  9 12 15 18 21 24 27 30]


26. Buatlah array NumPy yang berisi 5 nilai dengan jarak linier antara 0 dan 1.


In [77]:
arr = np.linspace(0, 1, 5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


27. Buatlah array NumPy dengan elemen integer 16-bit.


In [78]:
arr = np.array([1, 2, 3, 4, 5], dtype=np.int16)
print(arr.dtype)
print(arr)

int16
[1 2 3 4 5]


28. Buatlah array NumPy acak dengan panjang 6, lalu urutkan elemennya.


In [79]:
arr = np.random.randint(1, 100, 6) 
sorting = np.sort(arr)
print("Array acak:", arr)
print("Array setelah diurutkan:", sorting)

Array acak: [41 80 30 39 77 35]
Array setelah diurutkan: [30 35 39 41 77 80]


29. Gabungkan dua array NumPy satu dimensi [7, 8, 9] dan [10, 11, 12].


In [80]:
arr1 = np.array([7, 8, 9])
arr2 = np.array([10, 11, 12])

gabung = np.concatenate((arr1, arr2))
print(gabung)

[ 7  8  9 10 11 12]


30. Gabungkan dua array NumPy dua dimensi (misalnya, 2x3 dan 2x5) secara
horizontal.


In [81]:
arrA = np.array([[4, 8, 4], [9, 2, 1]])
arrB = np.array([[6, 8, 9, 4, 8], [8, 7, 2, 1, 1]]) 

merged_2d = np.concatenate((arrA, arrB), axis=1)
print("Array pertama:\n", arrA)
print("Array kedua:\n", arrB)
print("Array gabungan secara horizontal:\n", merged_2d)

Array pertama:
 [[4 8 4]
 [9 2 1]]
Array kedua:
 [[6 8 9 4 8]
 [8 7 2 1 1]]
Array gabungan secara horizontal:
 [[4 8 4 6 8 9 4 8]
 [9 2 1 8 7 2 1 1]]


31. Tentukan jumlah dimensi dari array NumPy yang berisi nilai acak.


In [82]:
arr = np.random.rand(3, 4, 2) 
print(arr)
print("Jumlah dimensi:", arr.ndim)

[[[9.23886849e-01 4.82964290e-01]
  [2.74560334e-01 7.17878687e-01]
  [9.46166481e-01 5.06034349e-01]
  [7.75113035e-01 5.02780353e-01]]

 [[5.11915742e-01 7.12805479e-01]
  [3.82419954e-01 6.85057886e-01]
  [7.88377901e-01 2.18813906e-01]
  [5.14606618e-01 4.71876154e-01]]

 [[3.20769911e-01 8.04071891e-01]
  [9.10845360e-01 3.46907324e-01]
  [7.71834383e-01 3.63655536e-04]
  [1.41561475e-01 6.33445337e-02]]]
Jumlah dimensi: 3


32. Tentukan jumlah total elemen dari array NumPy yang berisi nilai acak.


In [83]:
print("Jumlah total elemen:", arr.size)

Jumlah total elemen: 24


33. Tampilkan tupel bilangan bulat yang menunjukkan bentuk (shape) dari array
NumPy yang berisi nilai acak.

In [84]:
print("Shape dari array:", arr.shape)

Shape dari array: (3, 4, 2)


34. Ubahlah array NumPy satu dimensi [1, 2, 3, 4, 5, 6, 7, 8] menjadi matriks dua
dimensi (4 baris dan 2 kolom).


In [85]:
satu = np.array([1, 2, 3, 4, 5, 6, 7, 8])
dua = satu.reshape(2, 4)
print(dua)

[[1 2 3 4]
 [5 6 7 8]]


35. Ubahlah bentuk array NumPy yang berisi nilai acak menjadi matriks baru
dengan ukuran 2x4.


In [86]:
acak = np.random.randint(1, 100, 8)
print(acak)
matriks = acak.reshape((2, 4))
print(matriks)

[58 97 21 22  2 74  6 87]
[[58 97 21 22]
 [ 2 74  6 87]]


36. Dengan array NumPy yang berisi nilai acak dari 0 hingga 9, akses nilai pada
indeks ke-3.


In [87]:
acak = np.random.randint(0, 10, 10)
print("Array acak:", acak)

indeks_ke_3 = acak[3]
print("Nilai pada indeks ke-3:", indeks_ke_3)

Array acak: [1 4 7 4 8 8 0 8 8 4]
Nilai pada indeks ke-3: 4


37. Dengan array NumPy yang berisi nilai acak dari 0 hingga 9, temukan posisi
(indeks) dari nilai 7.


In [88]:
acak = np.random.randint(0, 10, 10)
print("Array acak:", acak)

temukan = np.where(acak == 7)
print("Indeks elemen dengan nilai 7:", temukan)

Array acak: [1 1 4 3 6 7 5 8 2 5]
Indeks elemen dengan nilai 7: (array([5]),)


38. Reverse array NumPy satu dimensi [1, 2, 3, 4, 5, 6].


In [89]:
array = np.array([1, 2, 3, 4, 5, 6])
print(array)
putar = np.flip(array)
print(putar)

[1 2 3 4 5 6]
[6 5 4 3 2 1]


39. Reverse baris dari array NumPy dua dimensi [[1, 2], [3, 4], [5, 6]].

In [90]:
array = np.array([[1, 2], [3, 4], [5, 6]])
print(array)
balik = np.flip(array, axis=0)
print(balik)

[[1 2]
 [3 4]
 [5 6]]
[[5 6]
 [3 4]
 [1 2]]


40. Buatlah kode python dari array pada gambar sbb:

In [91]:
arr = np.array([
    [3, 6, 9, 12],
    [15, 18, 21, 24],
    [27, 30, 33, 36],
    [39, 42, 45, 48],
    [51, 54, 57, 60]
])

result = np.take(arr, indices=[1, 3], axis=1) 

print("Array dari baris ganjil dan kolom genap:")
print(result)

Array dari baris ganjil dan kolom genap:
[[ 6 12]
 [18 24]
 [30 36]
 [42 48]
 [54 60]]


<strong>C. Soal Bersambung
</strong>

41. Buatlah array dua dimensi dari gambar sbb:


In [92]:

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


42. Akses dan tampilkan elemen pada baris kedua dan kolom kedua.


In [93]:
elemen_2_2 = arr[1, 1]  
print("Elemen pada baris kedua dan kolom kedua:", elemen_2_2)

Elemen pada baris kedua dan kolom kedua: 5


43. Ambil subset dari array dua dimensi tersebut yang terdiri dari dua baris pertama dan
dua kolom pertama.


In [94]:
subset = arr[:2, :2]
print("Subset dua baris pertama dan dua kolom pertama:\n", subset)


Subset dua baris pertama dan dua kolom pertama:
 [[1 2]
 [4 5]]


44. Ubah nilai elemen pada baris ketiga dan kolom ketiga dalam array menjadi 100.


In [95]:
arr[2, 2] = 100
print("Array setelah mengubah elemen (3,3) menjadi 100:\n", arr)

Array setelah mengubah elemen (3,3) menjadi 100:
 [[  1   2   3]
 [  4   5   6]
 [  7   8 100]]


45. Konversi elemen menjadi float.

In [96]:
arr_float = arr.astype(np.float64)
print("Array setelah dikonversi menjadi float:\n", arr_float)

Array setelah dikonversi menjadi float:
 [[  1.   2.   3.]
 [  4.   5.   6.]
 [  7.   8. 100.]]
